# Generated by Django 5.1.7 on 2025-03-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatedResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.TextField(max_length=1024)),
                ('result', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'calculated_result',
                'verbose_name_plural': 'calculated_results',
                'db_table': 'calc_result',
            },
        ),
    ]
